[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.4.6"
piston_window = "0.120.0"
find_folder = "0.3.0"
rusttype = "0.9"

[profile.release]
opt-level = 0
lto = true
codegen-units = 1
panic = "abort"